### ISSUE TITLE
Provide alternative store providers

### ISSUE THREAD

**Issue by claudiodangelis** [gingivitis/i3-pomodoro#2]
Thanks for this pomodoro! It would be great to have more options for providing the store, other than Redis. Keeping the port 6379 busy and a full Redis instance up just to support a simple program might not always be a viable option.

If you're interested but don't have time for this, I can work on it.

**Comment by odontogenic** [comment]
I have Redis running for several other projects but I understand your point. Unfortunately, I do not have time to maintain/upgrade this project atm. Please take a stab at some alternate backends :+1:
